import { defineConfig } from "vite";
import tailwindcss from "@tailwindcss/vite";

export default defineConfig({
  base: "/lecture-kit/",
  plugins: [tailwindcss()],
  build: {
    rollupOptions: {
      input: {
        main: "index.html",
        "dmv1-index": "courses/2026-digital-media-visual-1/index.html",
        "dmv1-chop": "courses/2026-digital-media-visual-1/chop-audio-reactive.html",
        "dmv1-chop-slides": "courses/2026-digital-media-visual-1/slides/chop-audio-reactive.html",
        "dmv1-audio-advanced": "courses/2026-digital-media-visual-1/audio-reactive-advanced.html",
        "dmv1-audio-advanced-slides": "courses/2026-digital-media-visual-1/slides/audio-reactive-advanced.html",
        "cc-index": "courses/claude-code-intro/index.html",
        "cc-level2": "courses/claude-code-intro/level-2-basics.html",
        "vtc-index": "courses/vibe-to-code/index.html",
        "vtc-week01": "courses/vibe-to-code/week-01.html",
        "vtc-week02": "courses/vibe-to-code/week-02.html",
        "vtc-week03": "courses/vibe-to-code/week-03.html",
        "comfyui-index": "courses/comfyui-basics/index.html",
        "comfyui-week03": "courses/comfyui-basics/week-03.html",
        "net-index": "courses/network-for-artists/index.html",
        "papri-index": "courses/papri-ai-workshop/index.html",
        "papri-week01": "courses/papri-ai-workshop/week-01.html",
        "fh-index": "courses/feed-hijacking/index.html",
        "fh-week01": "courses/feed-hijacking/week-01.html",
        "fh-week02": "courses/feed-hijacking/week-02.html",
        "fh-week03": "courses/feed-hijacking/week-03.html",
        "fh-week04": "courses/feed-hijacking/week-04.html",
        "nca-index": "courses/nca-touchdesigner/index.html",
        "nca-week01": "courses/nca-touchdesigner/week-01.html",
        "nca-week02": "courses/nca-touchdesigner/week-02.html",
        "nca-week03": "courses/nca-touchdesigner/week-03.html",
        "nca-week04": "courses/nca-touchdesigner/week-04.html",
        "nca-week05": "courses/nca-touchdesigner/week-05.html",
        "nca-week06": "courses/nca-touchdesigner/week-06.html",
        "nca-week07": "courses/nca-touchdesigner/week-07.html",
        "nca-week08": "courses/nca-touchdesigner/week-08.html",
        "nca-week09": "courses/nca-touchdesigner/week-09.html",
        "nca-week10": "courses/nca-touchdesigner/week-10.html",
        "nca-week11": "courses/nca-touchdesigner/week-11.html",
        "nca-week12": "courses/nca-touchdesigner/week-12.html",
        "nca-week13": "courses/nca-touchdesigner/week-13.html",
        "nca-week14": "courses/nca-touchdesigner/week-14.html",
        "nca-week15": "courses/nca-touchdesigner/week-15.html",
      },
    },
  },
});
